spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  #======================================
  # MySQL 配置项
  #
  datasource:
    url: jdbc:mysql://119.23.149.25:3306/fqfx_syjxzx?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: Daedalus@130
    initial-size: 5
    max-idle: 10
    min-idle: 5
    max-wait: 10000

  #========================
  # 前端模板配置
  thymeleaf:
    cache: false
    mode: HTML5

server:
  tomcat:
    uri-encoding: UTF-8

